# Generated by Django 2.2.6 on 2019-10-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('boss_id', models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='番号')),
                ('boss_name', models.CharField(max_length=255, verbose_name='ボス名')),
                ('max_hit_point', models.IntegerField(verbose_name='HP')),
                ('target', models.CharField(max_length=255, verbose_name='ダメージ目安')),
            ],
            options={
                'db_table': 'boss',
            },
        ),
        migrations.CreateModel(
            name='ClanMembers',
            fields=[
                ('member_id', models.CharField(default='', max_length=255, primary_key=True, serialize=False, verbose_name='メンバーID')),
                ('member_name', models.CharField(max_length=255, verbose_name='メンバー名')),
                ('is_member', models.BooleanField(default=False, verbose_name='正式メンバー')),
            ],
            options={
                'db_table': 'clan_members',
            },
        ),
        migrations.CreateModel(
            name='CurrentBoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_point', models.IntegerField(verbose_name='残りHP')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanbattle.Boss', verbose_name='ボス')),
            ],
            options={
                'db_table': 'current_boss',
            },
        ),
        migrations.CreateModel(
            name='CarryOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carried_at', models.DateTimeField(verbose_name='処理日')),
                ('time', models.IntegerField(verbose_name='持ち越し時間')),
                ('is_attack', models.BooleanField(default=False, verbose_name='凸済み')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanbattle.Boss', verbose_name='ボス')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanbattle.ClanMembers', verbose_name='メンバー')),
            ],
            options={
                'db_table': 'carry_over',
            },
        ),
        migrations.CreateModel(
            name='BossReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(verbose_name='予約日')),
                ('is_attack', models.BooleanField(default=False, verbose_name='凸済み')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='キャンセル')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanbattle.Boss', verbose_name='ボス')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanbattle.ClanMembers', verbose_name='メンバー')),
            ],
            options={
                'db_table': 'boss_reserve',
            },
        ),
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_time', models.DateTimeField(verbose_name='凸時間')),
                ('damage', models.IntegerField(verbose_name='ダメージ')),
                ('score', models.IntegerField(verbose_name='スコア')),
                ('is_carry_over', models.IntegerField(verbose_name='持ち越し')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanbattle.Boss', verbose_name='ボス')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clanbattle.ClanMembers', verbose_name='メンバー')),
            ],
            options={
                'db_table': 'attack_log',
            },
        ),
    ]
