# Generated by Django 2.2.6 on 2019-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clanbattle', '0003_attacklog_loop_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacklog',
            name='attack_weight',
            field=models.FloatField(default=0, verbose_name='重み'),
        ),
    ]
